// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: game_protos.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PieceType int32

const (
	PieceType_PAWN   PieceType = 0
	PieceType_ROOK   PieceType = 1
	PieceType_KNIGHT PieceType = 2
	PieceType_BISHOP PieceType = 3
	PieceType_QUEEN  PieceType = 4
	PieceType_KING   PieceType = 5
)

// Enum value maps for PieceType.
var (
	PieceType_name = map[int32]string{
		0: "PAWN",
		1: "ROOK",
		2: "KNIGHT",
		3: "BISHOP",
		4: "QUEEN",
		5: "KING",
	}
	PieceType_value = map[string]int32{
		"PAWN":   0,
		"ROOK":   1,
		"KNIGHT": 2,
		"BISHOP": 3,
		"QUEEN":  4,
		"KING":   5,
	}
)

func (x PieceType) Enum() *PieceType {
	p := new(PieceType)
	*p = x
	return p
}

func (x PieceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PieceType) Descriptor() protoreflect.EnumDescriptor {
	return file_game_protos_proto_enumTypes[0].Descriptor()
}

func (PieceType) Type() protoreflect.EnumType {
	return &file_game_protos_proto_enumTypes[0]
}

func (x PieceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PieceType.Descriptor instead.
func (PieceType) EnumDescriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{0}
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveFrom      string                 `protobuf:"bytes,1,opt,name=move_from,json=moveFrom,proto3" json:"move_from,omitempty"`
	MoveTo        string                 `protobuf:"bytes,2,opt,name=move_to,json=moveTo,proto3" json:"move_to,omitempty"`
	IsWhite       bool                   `protobuf:"varint,3,opt,name=is_white,json=isWhite,proto3" json:"is_white,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_game_protos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{0}
}

func (x *Move) GetMoveFrom() string {
	if x != nil {
		return x.MoveFrom
	}
	return ""
}

func (x *Move) GetMoveTo() string {
	if x != nil {
		return x.MoveTo
	}
	return ""
}

func (x *Move) GetIsWhite() bool {
	if x != nil {
		return x.IsWhite
	}
	return false
}

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerRank    int32                  `protobuf:"varint,2,opt,name=player_rank,json=playerRank,proto3" json:"player_rank,omitempty"`
	Duration      int32                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_game_protos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CreateGameRequest) GetPlayerRank() int32 {
	if x != nil {
		return x.PlayerRank
	}
	return 0
}

func (x *CreateGameRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_game_protos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGameResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type MakeMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Move          *Move                  `protobuf:"bytes,3,opt,name=move,proto3" json:"move,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveRequest) Reset() {
	*x = MakeMoveRequest{}
	mi := &file_game_protos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveRequest) ProtoMessage() {}

func (x *MakeMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveRequest.ProtoReflect.Descriptor instead.
func (*MakeMoveRequest) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{3}
}

func (x *MakeMoveRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *MakeMoveRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MakeMoveRequest) GetMove() *Move {
	if x != nil {
		return x.Move
	}
	return nil
}

type MakeMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeMoveResponse) Reset() {
	*x = MakeMoveResponse{}
	mi := &file_game_protos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeMoveResponse) ProtoMessage() {}

func (x *MakeMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeMoveResponse.ProtoReflect.Descriptor instead.
func (*MakeMoveResponse) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{4}
}

func (x *MakeMoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MakeMoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGameStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStatsRequest) Reset() {
	*x = GetGameStatsRequest{}
	mi := &file_game_protos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatsRequest) ProtoMessage() {}

func (x *GetGameStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatsRequest.ProtoReflect.Descriptor instead.
func (*GetGameStatsRequest) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{5}
}

func (x *GetGameStatsRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

type GetGameStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moves         []*Move                `protobuf:"bytes,1,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameStatsResponse) Reset() {
	*x = GetGameStatsResponse{}
	mi := &file_game_protos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameStatsResponse) ProtoMessage() {}

func (x *GetGameStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameStatsResponse.ProtoReflect.Descriptor instead.
func (*GetGameStatsResponse) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{6}
}

func (x *GetGameStatsResponse) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

type Piece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PieceType              `protobuf:"varint,1,opt,name=type,proto3,enum=game.PieceType" json:"type,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	IsWhite       bool                   `protobuf:"varint,3,opt,name=is_white,json=isWhite,proto3" json:"is_white,omitempty"`
	Captured      bool                   `protobuf:"varint,4,opt,name=captured,proto3" json:"captured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Piece) Reset() {
	*x = Piece{}
	mi := &file_game_protos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{7}
}

func (x *Piece) GetType() PieceType {
	if x != nil {
		return x.Type
	}
	return PieceType_PAWN
}

func (x *Piece) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Piece) GetIsWhite() bool {
	if x != nil {
		return x.IsWhite
	}
	return false
}

func (x *Piece) GetCaptured() bool {
	if x != nil {
		return x.Captured
	}
	return false
}

type Game struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GameId         string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Player1        string                 `protobuf:"bytes,2,opt,name=player1,proto3" json:"player1,omitempty"`
	Player2        string                 `protobuf:"bytes,3,opt,name=player2,proto3" json:"player2,omitempty"`
	Player1IsWhite bool                   `protobuf:"varint,4,opt,name=player1_is_white,json=player1IsWhite,proto3" json:"player1_is_white,omitempty"`
	Moves          []*Move                `protobuf:"bytes,5,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_game_protos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_game_protos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_game_protos_proto_rawDescGZIP(), []int{8}
}

func (x *Game) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *Game) GetPlayer1() string {
	if x != nil {
		return x.Player1
	}
	return ""
}

func (x *Game) GetPlayer2() string {
	if x != nil {
		return x.Player2
	}
	return ""
}

func (x *Game) GetPlayer1IsWhite() bool {
	if x != nil {
		return x.Player1IsWhite
	}
	return false
}

func (x *Game) GetMoves() []*Move {
	if x != nil {
		return x.Moves
	}
	return nil
}

var File_game_protos_proto protoreflect.FileDescriptor

var file_game_protos_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x57, 0x0a, 0x04, 0x4d, 0x6f, 0x76,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x17,
	0x0a, 0x07, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x77, 0x68,
	0x69, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x57, 0x68, 0x69,
	0x74, 0x65, 0x22, 0x6d, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x72,
	0x61, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x61, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x2d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64,
	0x22, 0x67, 0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x6d, 0x6f, 0x76,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0x46, 0x0a, 0x10, 0x4d, 0x61, 0x6b,
	0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x2e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x22, 0x38, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x6d, 0x6f, 0x76,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x22, 0x7f, 0x0a, 0x05, 0x50,
	0x69, 0x65, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x69, 0x65, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x77, 0x68, 0x69, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x64, 0x22, 0x9f, 0x01, 0x0a,
	0x04, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x32, 0x12, 0x28, 0x0a, 0x10, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x31, 0x5f, 0x69, 0x73,
	0x5f, 0x77, 0x68, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x31, 0x49, 0x73, 0x57, 0x68, 0x69, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x05,
	0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x2a, 0x4c,
	0x0a, 0x09, 0x50, 0x69, 0x65, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x41, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x4f, 0x4b, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x4b, 0x4e, 0x49, 0x47, 0x48, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x42,
	0x49, 0x53, 0x48, 0x4f, 0x50, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x45, 0x4e,
	0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x32, 0xd0, 0x01, 0x0a,
	0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x39, 0x0a, 0x08,
	0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x14, 0x5a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_game_protos_proto_rawDescOnce sync.Once
	file_game_protos_proto_rawDescData []byte
)

func file_game_protos_proto_rawDescGZIP() []byte {
	file_game_protos_proto_rawDescOnce.Do(func() {
		file_game_protos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_protos_proto_rawDesc), len(file_game_protos_proto_rawDesc)))
	})
	return file_game_protos_proto_rawDescData
}

var file_game_protos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_game_protos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_game_protos_proto_goTypes = []any{
	(PieceType)(0),               // 0: game.PieceType
	(*Move)(nil),                 // 1: game.Move
	(*CreateGameRequest)(nil),    // 2: game.CreateGameRequest
	(*CreateGameResponse)(nil),   // 3: game.CreateGameResponse
	(*MakeMoveRequest)(nil),      // 4: game.MakeMoveRequest
	(*MakeMoveResponse)(nil),     // 5: game.MakeMoveResponse
	(*GetGameStatsRequest)(nil),  // 6: game.GetGameStatsRequest
	(*GetGameStatsResponse)(nil), // 7: game.GetGameStatsResponse
	(*Piece)(nil),                // 8: game.Piece
	(*Game)(nil),                 // 9: game.Game
}
var file_game_protos_proto_depIdxs = []int32{
	1, // 0: game.MakeMoveRequest.move:type_name -> game.Move
	1, // 1: game.GetGameStatsResponse.moves:type_name -> game.Move
	0, // 2: game.Piece.type:type_name -> game.PieceType
	1, // 3: game.Game.moves:type_name -> game.Move
	4, // 4: game.GameService.MakeMove:input_type -> game.MakeMoveRequest
	2, // 5: game.GameService.CreateGame:input_type -> game.CreateGameRequest
	6, // 6: game.GameService.GetGameStats:input_type -> game.GetGameStatsRequest
	5, // 7: game.GameService.MakeMove:output_type -> game.MakeMoveResponse
	3, // 8: game.GameService.CreateGame:output_type -> game.CreateGameResponse
	7, // 9: game.GameService.GetGameStats:output_type -> game.GetGameStatsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_game_protos_proto_init() }
func file_game_protos_proto_init() {
	if File_game_protos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_protos_proto_rawDesc), len(file_game_protos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_protos_proto_goTypes,
		DependencyIndexes: file_game_protos_proto_depIdxs,
		EnumInfos:         file_game_protos_proto_enumTypes,
		MessageInfos:      file_game_protos_proto_msgTypes,
	}.Build()
	File_game_protos_proto = out.File
	file_game_protos_proto_goTypes = nil
	file_game_protos_proto_depIdxs = nil
}
